lesson17
Eduard2509/course_nix pull request #8
Opened 2022-08-04 23:48 UTC by Eduard2509

IO/NIO

2022-08-04 23:49 UTC, Eduard2509 commented
![](https://github.trello.services/images/mini-trello-icon.png) [IO/NIO](https://trello.com/c/HreljYCS/85-io-nio)

2022-08-05 20:55 UTC, Fabolo12 requested changes

2022-08-05 20:55 UTC, Fabolo12 commented on src/main/java/com/command/ReadFromFileJson.java
> +        File file = new File("src/main/resources/auto.json");
Чтение с файла не верное

2022-08-06 22:13 UTC, Fabolo12 approved these changes

2022-08-07 15:39 UTC, Fabolo12 approved these changes

2022-08-07 15:39 UTC, Fabolo12 commented on src/main/java/com/command/ReadFromFileXml.java
> +
test

2022-08-09 15:28 UTC, merged